---
version: '3'

services:
  db:
    image: mysql:5.7
    container_name: ddrupal-db
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ddrupal-db-admin
    restart: always
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_ARBITRARY: "1"
    ports:
      - 7777:80

  drupal:
    build: .
    container_name: ddrupal-web
    restart: always
    ports:
      - "80:80"
    working_dir: /opt
    volumes:
      - .:/opt:z
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    command: bash -c "composer update && rm /var/www/html && ln -s /opt/web /var/www/html && /usr/local/bin/apache2-foreground"

